### ISSUE TITLE
Firefox hover animation issue.

### ISSUE THREAD

**Issue by iRaul** [iRaul/twitter-corners#1]

**Comment by JTBrinkmann** [comment]
I couldn't quite fix the the root of the problem, but as a quick and dirty workaround I am using
```css
.twitter-corner:hover .bird-wing {
 animation: fly .4s linear 2 forwards;
 transform-origin: right center;
 -moz-transform-origin: 80px center;
}
@keyframes fly {
 0% {
  transform: translateX(0);
 }
 50% {
  transform: rotateY(-180deg) translateX(-50%) translateY(10%) rotateZ(-50deg);
  -moz-transform: translateY(-8px) rotateY(-180deg) rotateX(-50deg);
 }
 100% {
  transform: translateX(0);
 }
}
```
(the `-moz-` lines are added). The animation isn't the exactly same, but it looks acceptably close to me.
I think it only works if the size is 80x80 pixel. I might investigate this further if I find the time.
